{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "50ea74b2-6ec6-47bc-aae9-27897a843f1d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: ray[client] in /home/nikos/.local/lib/python3.10/site-packages (2.9.0)\n",
      "Requirement already satisfied: frozenlist in /home/nikos/.local/lib/python3.10/site-packages (from ray[client]) (1.4.1)\n",
      "Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from ray[client]) (5.4.1)\n",
      "Requirement already satisfied: packaging in /home/nikos/.local/lib/python3.10/site-packages (from ray[client]) (23.2)\n",
      "Requirement already satisfied: filelock in /home/nikos/.local/lib/python3.10/site-packages (from ray[client]) (3.13.0)\n",
      "Requirement already satisfied: requests in /home/nikos/.local/lib/python3.10/site-packages (from ray[client]) (2.31.0)\n",
      "Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in /home/nikos/.local/lib/python3.10/site-packages (from ray[client]) (4.25.1)\n",
      "Requirement already satisfied: aiosignal in /home/nikos/.local/lib/python3.10/site-packages (from ray[client]) (1.3.1)\n",
      "Requirement already satisfied: jsonschema in /home/nikos/.local/lib/python3.10/site-packages (from ray[client]) (4.19.2)\n",
      "Requirement already satisfied: click>=7.0 in /usr/lib/python3/dist-packages (from ray[client]) (8.0.3)\n",
      "Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /home/nikos/.local/lib/python3.10/site-packages (from ray[client]) (1.0.7)\n",
      "Requirement already satisfied: grpcio in /home/nikos/.local/lib/python3.10/site-packages (from ray[client]) (1.60.0)\n",
      "Requirement already satisfied: referencing>=0.28.4 in /home/nikos/.local/lib/python3.10/site-packages (from jsonschema->ray[client]) (0.30.2)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/nikos/.local/lib/python3.10/site-packages (from jsonschema->ray[client]) (2023.7.1)\n",
      "Requirement already satisfied: attrs>=22.2.0 in /home/nikos/.local/lib/python3.10/site-packages (from jsonschema->ray[client]) (23.1.0)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in /home/nikos/.local/lib/python3.10/site-packages (from jsonschema->ray[client]) (0.10.6)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /home/nikos/.local/lib/python3.10/site-packages (from requests->ray[client]) (3.3.1)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->ray[client]) (2020.6.20)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->ray[client]) (3.3)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->ray[client]) (1.26.5)\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: transformers in /home/nikos/.local/lib/python3.10/site-packages (4.36.2)\n",
      "Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /home/nikos/.local/lib/python3.10/site-packages (from transformers) (0.20.2)\n",
      "Requirement already satisfied: tqdm>=4.27 in /home/nikos/.local/lib/python3.10/site-packages (from transformers) (4.66.1)\n",
      "Requirement already satisfied: numpy>=1.17 in /home/nikos/.local/lib/python3.10/site-packages (from transformers) (1.26.1)\n",
      "Requirement already satisfied: safetensors>=0.3.1 in /home/nikos/.local/lib/python3.10/site-packages (from transformers) (0.4.1)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from transformers) (5.4.1)\n",
      "Requirement already satisfied: regex!=2019.12.17 in /home/nikos/.local/lib/python3.10/site-packages (from transformers) (2023.12.25)\n",
      "Requirement already satisfied: packaging>=20.0 in /home/nikos/.local/lib/python3.10/site-packages (from transformers) (23.2)\n",
      "Requirement already satisfied: filelock in /home/nikos/.local/lib/python3.10/site-packages (from transformers) (3.13.0)\n",
      "Requirement already satisfied: tokenizers<0.19,>=0.14 in /home/nikos/.local/lib/python3.10/site-packages (from transformers) (0.15.0)\n",
      "Requirement already satisfied: requests in /home/nikos/.local/lib/python3.10/site-packages (from transformers) (2.31.0)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in /home/nikos/.local/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.19.3->transformers) (2023.10.0)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/nikos/.local/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.19.3->transformers) (4.8.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /home/nikos/.local/lib/python3.10/site-packages (from requests->transformers) (3.3.1)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->transformers) (1.26.5)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->transformers) (2020.6.20)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->transformers) (3.3)\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: accelerate in /home/nikos/.local/lib/python3.10/site-packages (0.25.0)\n",
      "Requirement already satisfied: huggingface-hub in /home/nikos/.local/lib/python3.10/site-packages (from accelerate) (0.20.2)\n",
      "Requirement already satisfied: psutil in /home/nikos/.local/lib/python3.10/site-packages (from accelerate) (5.9.6)\n",
      "Requirement already satisfied: safetensors>=0.3.1 in /home/nikos/.local/lib/python3.10/site-packages (from accelerate) (0.4.1)\n",
      "Requirement already satisfied: torch>=1.10.0 in /home/nikos/.local/lib/python3.10/site-packages (from accelerate) (2.1.2)\n",
      "Requirement already satisfied: numpy>=1.17 in /home/nikos/.local/lib/python3.10/site-packages (from accelerate) (1.26.1)\n",
      "Requirement already satisfied: packaging>=20.0 in /home/nikos/.local/lib/python3.10/site-packages (from accelerate) (23.2)\n",
      "Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from accelerate) (5.4.1)\n",
      "Requirement already satisfied: nvidia-nccl-cu12==2.18.1 in /home/nikos/.local/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (2.18.1)\n",
      "Requirement already satisfied: jinja2 in /home/nikos/.local/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (3.1.2)\n",
      "Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/nikos/.local/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (10.3.2.106)\n",
      "Requirement already satisfied: typing-extensions in /home/nikos/.local/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (4.8.0)\n",
      "Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/nikos/.local/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (12.1.105)\n",
      "Requirement already satisfied: fsspec in /home/nikos/.local/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (2023.10.0)\n",
      "Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/nikos/.local/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (12.1.105)\n",
      "Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/nikos/.local/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (12.1.105)\n",
      "Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/nikos/.local/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (11.4.5.107)\n",
      "Requirement already satisfied: networkx in /home/nikos/.local/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (3.2.1)\n",
      "Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/nikos/.local/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (12.1.0.106)\n",
      "Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/nikos/.local/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (12.1.3.1)\n",
      "Requirement already satisfied: triton==2.1.0 in /home/nikos/.local/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (2.1.0)\n",
      "Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/nikos/.local/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (12.1.105)\n",
      "Requirement already satisfied: sympy in /home/nikos/.local/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (1.12)\n",
      "Requirement already satisfied: filelock in /home/nikos/.local/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (3.13.0)\n",
      "Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /home/nikos/.local/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (8.9.2.26)\n",
      "Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/nikos/.local/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (11.0.2.54)\n",
      "Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/nikos/.local/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.10.0->accelerate) (12.3.101)\n",
      "Requirement already satisfied: requests in /home/nikos/.local/lib/python3.10/site-packages (from huggingface-hub->accelerate) (2.31.0)\n",
      "Requirement already satisfied: tqdm>=4.42.1 in /home/nikos/.local/lib/python3.10/site-packages (from huggingface-hub->accelerate) (4.66.1)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /usr/lib/python3/dist-packages (from jinja2->torch>=1.10.0->accelerate) (2.0.1)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->huggingface-hub->accelerate) (2020.6.20)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->huggingface-hub->accelerate) (1.26.5)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /home/nikos/.local/lib/python3.10/site-packages (from requests->huggingface-hub->accelerate) (3.3.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->huggingface-hub->accelerate) (3.3)\n",
      "Requirement already satisfied: mpmath>=0.19 in /home/nikos/.local/lib/python3.10/site-packages (from sympy->torch>=1.10.0->accelerate) (1.3.0)\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: evaluate in /home/nikos/.local/lib/python3.10/site-packages (0.4.1)\n",
      "Requirement already satisfied: pandas in /home/nikos/.local/lib/python3.10/site-packages (from evaluate) (2.1.2)\n",
      "Requirement already satisfied: huggingface-hub>=0.7.0 in /home/nikos/.local/lib/python3.10/site-packages (from evaluate) (0.20.2)\n",
      "Requirement already satisfied: multiprocess in /home/nikos/.local/lib/python3.10/site-packages (from evaluate) (0.70.15)\n",
      "Requirement already satisfied: tqdm>=4.62.1 in /home/nikos/.local/lib/python3.10/site-packages (from evaluate) (4.66.1)\n",
      "Requirement already satisfied: numpy>=1.17 in /home/nikos/.local/lib/python3.10/site-packages (from evaluate) (1.26.1)\n",
      "Requirement already satisfied: xxhash in /home/nikos/.local/lib/python3.10/site-packages (from evaluate) (3.4.1)\n",
      "Requirement already satisfied: requests>=2.19.0 in /home/nikos/.local/lib/python3.10/site-packages (from evaluate) (2.31.0)\n",
      "Requirement already satisfied: datasets>=2.0.0 in /home/nikos/.local/lib/python3.10/site-packages (from evaluate) (2.16.1)\n",
      "Requirement already satisfied: fsspec[http]>=2021.05.0 in /home/nikos/.local/lib/python3.10/site-packages (from evaluate) (2023.10.0)\n",
      "Requirement already satisfied: responses<0.19 in /home/nikos/.local/lib/python3.10/site-packages (from evaluate) (0.18.0)\n",
      "Requirement already satisfied: dill in /home/nikos/.local/lib/python3.10/site-packages (from evaluate) (0.3.7)\n",
      "Requirement already satisfied: packaging in /home/nikos/.local/lib/python3.10/site-packages (from evaluate) (23.2)\n",
      "Requirement already satisfied: aiohttp in /home/nikos/.local/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (3.9.1)\n",
      "Requirement already satisfied: filelock in /home/nikos/.local/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (3.13.0)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from datasets>=2.0.0->evaluate) (5.4.1)\n",
      "Requirement already satisfied: pyarrow>=8.0.0 in /home/nikos/.local/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (14.0.2)\n",
      "Requirement already satisfied: pyarrow-hotfix in /home/nikos/.local/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (0.6)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/nikos/.local/lib/python3.10/site-packages (from huggingface-hub>=0.7.0->evaluate) (4.8.0)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests>=2.19.0->evaluate) (1.26.5)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.19.0->evaluate) (2020.6.20)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.19.0->evaluate) (3.3)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /home/nikos/.local/lib/python3.10/site-packages (from requests>=2.19.0->evaluate) (3.3.1)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /home/nikos/.local/lib/python3.10/site-packages (from pandas->evaluate) (2.8.2)\n",
      "Requirement already satisfied: tzdata>=2022.1 in /home/nikos/.local/lib/python3.10/site-packages (from pandas->evaluate) (2023.3)\n",
      "Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas->evaluate) (2022.1)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /home/nikos/.local/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.0.4)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /home/nikos/.local/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.4.1)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /home/nikos/.local/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (23.1.0)\n",
      "Requirement already satisfied: async-timeout<5.0,>=4.0 in /home/nikos/.local/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (4.0.3)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /home/nikos/.local/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.9.4)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /home/nikos/.local/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.1)\n",
      "Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.16.0)\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: numpy in /home/nikos/.local/lib/python3.10/site-packages (1.26.1)\n"
     ]
    }
   ],
   "source": [
    "! pip install ray[client]\n",
    "! pip install transformers\n",
    "! pip install accelerate\n",
    "! pip install evaluate\n",
    "! pip install numpy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "8ab1a75c-af40-4bc9-a67c-e286b9d9fab9",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/nikos/workspace/ray-docker-compose/.venv/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n",
      "2024-01-11 19:50:45,334\tINFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.\n",
      "2024-01-11 19:50:45,427\tINFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.\n",
      "2024-01-11 19:50:45,447\tINFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.\n",
      "SIGTERM handler is not set because current thread is not the main thread.\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div class=\"lm-Widget p-Widget lm-Panel p-Panel jp-Cell-outputWrapper\">\n",
       "    <div style=\"margin-left: 50px;display: flex;flex-direction: row;align-items: center\">\n",
       "        <div class=\"jp-RenderedHTMLCommon\" style=\"display: flex; flex-direction: row;\">\n",
       "  <svg viewBox=\"0 0 567 224\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\" style=\"height: 3em;\">\n",
       "    <g clip-path=\"url(#clip0_4338_178347)\">\n",
       "        <path d=\"M341.29 165.561H355.29L330.13 129.051C345.63 123.991 354.21 112.051 354.21 94.2307C354.21 71.3707 338.72 58.1807 311.88 58.1807H271V165.561H283.27V131.661H311.8C314.25 131.661 316.71 131.501 319.01 131.351L341.25 165.561H341.29ZM283.29 119.851V70.0007H311.82C331.3 70.0007 342.34 78.2907 342.34 94.5507C342.34 111.271 331.34 119.861 311.82 119.861L283.29 119.851ZM451.4 138.411L463.4 165.561H476.74L428.74 58.1807H416L367.83 165.561H380.83L392.83 138.411H451.4ZM446.19 126.601H398L422 72.1407L446.24 126.601H446.19ZM526.11 128.741L566.91 58.1807H554.35L519.99 114.181L485.17 58.1807H472.44L514.01 129.181V165.541H526.13V128.741H526.11Z\" fill=\"var(--jp-ui-font-color0)\"/>\n",
       "        <path d=\"M82.35 104.44C84.0187 97.8827 87.8248 92.0678 93.1671 87.9146C98.5094 83.7614 105.083 81.5067 111.85 81.5067C118.617 81.5067 125.191 83.7614 130.533 87.9146C135.875 92.0678 139.681 97.8827 141.35 104.44H163.75C164.476 101.562 165.622 98.8057 167.15 96.2605L127.45 56.5605C121.071 60.3522 113.526 61.6823 106.235 60.3005C98.9443 58.9187 92.4094 54.9203 87.8602 49.0574C83.3109 43.1946 81.0609 35.8714 81.5332 28.4656C82.0056 21.0599 85.1679 14.0819 90.4252 8.8446C95.6824 3.60726 102.672 0.471508 110.08 0.0272655C117.487 -0.416977 124.802 1.86091 130.647 6.4324C136.493 11.0039 140.467 17.5539 141.821 24.8501C143.175 32.1463 141.816 39.6859 138 46.0505L177.69 85.7505C182.31 82.9877 187.58 81.4995 192.962 81.4375C198.345 81.3755 203.648 82.742 208.33 85.3976C213.012 88.0532 216.907 91.9029 219.616 96.5544C222.326 101.206 223.753 106.492 223.753 111.875C223.753 117.258 222.326 122.545 219.616 127.197C216.907 131.848 213.012 135.698 208.33 138.353C203.648 141.009 198.345 142.375 192.962 142.313C187.58 142.251 182.31 140.763 177.69 138L138 177.7C141.808 184.071 143.155 191.614 141.79 198.91C140.424 206.205 136.44 212.75 130.585 217.313C124.731 221.875 117.412 224.141 110.004 223.683C102.596 223.226 95.6103 220.077 90.3621 214.828C85.1139 209.58 81.9647 202.595 81.5072 195.187C81.0497 187.779 83.3154 180.459 87.878 174.605C92.4405 168.751 98.9853 164.766 106.281 163.401C113.576 162.035 121.119 163.383 127.49 167.19L167.19 127.49C165.664 124.941 164.518 122.182 163.79 119.3H141.39C139.721 125.858 135.915 131.673 130.573 135.826C125.231 139.98 118.657 142.234 111.89 142.234C105.123 142.234 98.5494 139.98 93.2071 135.826C87.8648 131.673 84.0587 125.858 82.39 119.3H60C58.1878 126.495 53.8086 132.78 47.6863 136.971C41.5641 141.163 34.1211 142.972 26.7579 142.059C19.3947 141.146 12.6191 137.574 7.70605 132.014C2.79302 126.454 0.0813599 119.29 0.0813599 111.87C0.0813599 104.451 2.79302 97.2871 7.70605 91.7272C12.6191 86.1673 19.3947 82.5947 26.7579 81.6817C34.1211 80.7686 41.5641 82.5781 47.6863 86.7696C53.8086 90.9611 58.1878 97.2456 60 104.44H82.35ZM100.86 204.32C103.407 206.868 106.759 208.453 110.345 208.806C113.93 209.159 117.527 208.258 120.522 206.256C123.517 204.254 125.725 201.276 126.771 197.828C127.816 194.38 127.633 190.677 126.253 187.349C124.874 184.021 122.383 181.274 119.205 179.577C116.027 177.88 112.359 177.337 108.826 178.042C105.293 178.746 102.113 180.654 99.8291 183.44C97.5451 186.226 96.2979 189.718 96.3 193.32C96.2985 195.364 96.7006 197.388 97.4831 199.275C98.2656 201.163 99.4132 202.877 100.86 204.32ZM204.32 122.88C206.868 120.333 208.453 116.981 208.806 113.396C209.159 109.811 208.258 106.214 206.256 103.219C204.254 100.223 201.275 98.0151 197.827 96.97C194.38 95.9249 190.676 96.1077 187.348 97.4873C184.02 98.8669 181.274 101.358 179.577 104.536C177.879 107.714 177.337 111.382 178.041 114.915C178.746 118.448 180.653 121.627 183.439 123.911C186.226 126.195 189.717 127.443 193.32 127.44C195.364 127.443 197.388 127.042 199.275 126.259C201.163 125.476 202.878 124.328 204.32 122.88ZM122.88 19.4205C120.333 16.8729 116.981 15.2876 113.395 14.9347C109.81 14.5817 106.213 15.483 103.218 17.4849C100.223 19.4868 98.0146 22.4654 96.9696 25.9131C95.9245 29.3608 96.1073 33.0642 97.4869 36.3922C98.8665 39.7202 101.358 42.4668 104.535 44.1639C107.713 45.861 111.381 46.4036 114.914 45.6992C118.447 44.9949 121.627 43.0871 123.911 40.301C126.195 37.515 127.442 34.0231 127.44 30.4205C127.44 28.3772 127.038 26.3539 126.255 24.4664C125.473 22.5788 124.326 20.8642 122.88 19.4205ZM19.42 100.86C16.8725 103.408 15.2872 106.76 14.9342 110.345C14.5813 113.93 15.4826 117.527 17.4844 120.522C19.4863 123.518 22.4649 125.726 25.9127 126.771C29.3604 127.816 33.0638 127.633 36.3918 126.254C39.7198 124.874 42.4664 122.383 44.1635 119.205C45.8606 116.027 46.4032 112.359 45.6988 108.826C44.9944 105.293 43.0866 102.114 40.3006 99.8296C37.5145 97.5455 34.0227 96.2983 30.42 96.3005C26.2938 96.3018 22.337 97.9421 19.42 100.86ZM100.86 100.86C98.3125 103.408 96.7272 106.76 96.3742 110.345C96.0213 113.93 96.9226 117.527 98.9244 120.522C100.926 123.518 103.905 125.726 107.353 126.771C110.8 127.816 114.504 127.633 117.832 126.254C121.16 124.874 123.906 122.383 125.604 119.205C127.301 116.027 127.843 112.359 127.139 108.826C126.434 105.293 124.527 102.114 121.741 99.8296C118.955 97.5455 115.463 96.2983 111.86 96.3005C109.817 96.299 107.793 96.701 105.905 97.4835C104.018 98.2661 102.303 99.4136 100.86 100.86Z\" fill=\"#00AEEF\"/>\n",
       "    </g>\n",
       "    <defs>\n",
       "        <clipPath id=\"clip0_4338_178347\">\n",
       "            <rect width=\"566.93\" height=\"223.75\" fill=\"white\"/>\n",
       "        </clipPath>\n",
       "    </defs>\n",
       "  </svg>\n",
       "</div>\n",
       "\n",
       "        <table class=\"jp-RenderedHTMLCommon\" style=\"border-collapse: collapse;color: var(--jp-ui-font-color1);font-size: var(--jp-ui-font-size1);\">\n",
       "    <tr>\n",
       "        <td style=\"text-align: left\"><b>Python version:</b></td>\n",
       "        <td style=\"text-align: left\"><b>3.8.10</b></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "        <td style=\"text-align: left\"><b>Ray version:</b></td>\n",
       "        <td style=\"text-align: left\"><b>2.9.0</b></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "    <td style=\"text-align: left\"><b>Dashboard:</b></td>\n",
       "    <td style=\"text-align: left\"><b><a href=\"http://88.197.52.51:8265\" target=\"_blank\">http://88.197.52.51:8265</a></b></td>\n",
       "</tr>\n",
       "\n",
       "</table>\n",
       "\n",
       "    </div>\n",
       "</div>\n"
      ],
      "text/plain": [
       "ClientContext(dashboard_url='88.197.52.51:8265', python_version='3.8.10', ray_version='2.9.0', ray_commit='9be5a16e3ccad0710bba08d0f75e9ff774ae6880', protocol_version='2023-06-27', _num_clients=1, _context_to_restore=<ray.util.client._ClientContext object at 0x7f83f9bc1d90>)"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import os\n",
    "\n",
    "import evaluate\n",
    "import numpy as np\n",
    "import evaluate\n",
    "from datasets import load_dataset\n",
    "from transformers import (\n",
    "    Trainer,\n",
    "    TrainingArguments,\n",
    "    AutoTokenizer,\n",
    "    AutoModelForSequenceClassification,\n",
    ")\n",
    "\n",
    "import ray.train.huggingface.transformers\n",
    "from ray.train import ScalingConfig\n",
    "from ray.train.torch import TorchTrainer\n",
    "import ray\n",
    "import torch\n",
    "\n",
    "ray.init(address='ray://thalis.madgik.di.uoa.gr:10001')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "f33139b0-4499-412b-8aee-d262f2afdd5c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m [output] This will use the new output engine with verbosity 1. To disable the new output and use the legacy output engine, set the environment variable RAY_AIR_NEW_OUTPUT=0. For more information, please see https://github.com/ray-project/ray/issues/36949\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m AIR_VERBOSITY is set, ignoring passed-in ProgressReporter for now.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m \n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m View detailed results here: /ray/TorchTrainer_2024-01-11_19-52-59\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m To visualize your results with TensorBoard, run: `tensorboard --logdir /root/ray_results/TorchTrainer_2024-01-11_19-52-59`\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[36m(TorchTrainer pid=990, ip=127.0.0.1)\u001b[0m The actor died unexpectedly before finishing this task.\n",
      "\u001b[36m(TorchTrainer pid=990, ip=127.0.0.1)\u001b[0m \tclass_name: \n",
      "\u001b[36m(TorchTrainer pid=990, ip=127.0.0.1)\u001b[0m \tactor_id: 87a6186050c65023aaa098b408000000\n",
      "\u001b[36m(TorchTrainer pid=990, ip=127.0.0.1)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[36m(TorchTrainer pid=990, ip=127.0.0.1)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/train/_internal/backend_executor.py\", line 190, in start\n",
      "\u001b[36m(TorchTrainer pid=990, ip=127.0.0.1)\u001b[0m     self._backend.on_start(self.worker_group, self._backend_config)\n",
      "\u001b[36m(TorchTrainer pid=990, ip=127.0.0.1)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/train/torch/config.py\", line 198, in on_start\n",
      "\u001b[36m(TorchTrainer pid=990, ip=127.0.0.1)\u001b[0m     ray.get(setup_futures)\n",
      "\u001b[36m(TorchTrainer pid=990, ip=127.0.0.1)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/_private/auto_init_hook.py\", line 22, in auto_init_wrapper\n",
      "\u001b[36m(TorchTrainer pid=990, ip=127.0.0.1)\u001b[0m     return fn(*args, **kwargs)\n",
      "\u001b[36m(TorchTrainer pid=990, ip=127.0.0.1)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "\u001b[36m(TorchTrainer pid=990, ip=127.0.0.1)\u001b[0m     return func(*args, **kwargs)\n",
      "\u001b[36m(TorchTrainer pid=990, ip=127.0.0.1)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/_private/worker.py\", line 2626, in get\n",
      "\u001b[36m(TorchTrainer pid=990, ip=127.0.0.1)\u001b[0m     raise value\n",
      "\u001b[36m(TorchTrainer pid=990, ip=127.0.0.1)\u001b[0m ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.\n",
      "\u001b[36m(TorchTrainer pid=990, ip=127.0.0.1)\u001b[0m \tclass_name: \n",
      "\u001b[36m(TorchTrainer pid=990, ip=127.0.0.1)\u001b[0m \tactor_id: 87a6186050c65023aaa098b408000000\n",
      "\u001b[36m(TorchTrainer pid=990, ip=127.0.0.1)\u001b[0m \n",
      "\u001b[36m(TorchTrainer pid=990, ip=127.0.0.1)\u001b[0m Failure occurred during startup. Restarting all workers and attempting to startup again.\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m Trial task failed for trial TorchTrainer_033e7_00000\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m     result = ray.get(future)\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/_private/auto_init_hook.py\", line 22, in auto_init_wrapper\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m     return fn(*args, **kwargs)\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m     return func(*args, **kwargs)\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/_private/worker.py\", line 2624, in get\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m     raise value.as_instanceof_cause()\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m ray.exceptions.RayTaskError(TypeError): \u001b[36mray::TrainTrainable.train()\u001b[39m (pid=990, ip=127.0.0.1, actor_id=5b4985f9e63ced70153674d008000000, repr=TorchTrainer)\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/tune/trainable/trainable.py\", line 342, in train\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m     raise skipped from exception_cause(skipped)\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/air/_internal/util.py\", line 88, in run\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m     self._ret = self._target(*self._args, **self._kwargs)\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/tune/trainable/function_trainable.py\", line 115, in <lambda>\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m     training_func=lambda: self._trainable_func(self.config),\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m   File \"/home/nikos/workspace/ray-docker-compose/.venv/lib/python3.8/site-packages/ray/train/base_trainer.py\", line 819, in _trainable_func\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m   File \"/home/nikos/workspace/ray-docker-compose/.venv/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py\", line 332, in _trainable_func\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m   File \"/home/nikos/workspace/ray-docker-compose/.venv/lib/python3.8/site-packages/ray/train/base_trainer.py\", line 729, in train_func\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/train/data_parallel_trainer.py\", line 464, in training_loop\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m     backend_executor.start()\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/train/_internal/backend_executor.py\", line 197, in start\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m     self._increment_failures()\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/train/_internal/backend_executor.py\", line 723, in _increment_failures\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m     raise failure\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m TypeError: exceptions must derive from BaseException\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m Trials did not complete: [TorchTrainer_033e7_00000]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m \n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m Training errored after 0 iterations at 2024-01-11 19:53:02. Total running time: 1min 48s\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m Error file: /root/ray_results/TorchTrainer_2024-01-11_19-51-12/TorchTrainer_033e7_00000_0_2024-01-11_19-51-14/error.txt\n",
      "\u001b[36m(TunerInternal pid=11894)\u001b[0m \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[36m(TrainTrainable pid=323, ip=127.0.0.1)\u001b[0m GPUs are detected in your Ray cluster, but GPU training is not enabled for this trainer. To enable GPU training, make sure to set `use_gpu` to True in your scaling config.\n",
      "\u001b[36m(TorchTrainer pid=323, ip=127.0.0.1)\u001b[0m GPUs are detected in your Ray cluster, but GPU training is not enabled for this trainer. To enable GPU training, make sure to set `use_gpu` to True in your scaling config.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m \n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m Training started without custom configuration.\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m \n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m Training errored after 0 iterations at 2024-01-11 19:53:15. Total running time: 14s\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m Error file: /root/ray_results/TorchTrainer_2024-01-11_19-52-59/TorchTrainer_42b96_00000_0_2024-01-11_19-53-00/error.txt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m Trial task failed for trial TorchTrainer_42b96_00000\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m     result = ray.get(future)\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/_private/auto_init_hook.py\", line 22, in auto_init_wrapper\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m     return fn(*args, **kwargs)\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m     return func(*args, **kwargs)\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/_private/worker.py\", line 2624, in get\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m     raise value.as_instanceof_cause()\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m ray.exceptions.RayTaskError(RayActorError): \u001b[36mray::TrainTrainable.train()\u001b[39m (pid=323, ip=127.0.0.1, actor_id=36cbebeaf9caa93bc26c198308000000, repr=TorchTrainer)\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/tune/trainable/trainable.py\", line 342, in train\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m     raise skipped from exception_cause(skipped)\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/air/_internal/util.py\", line 88, in run\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m     self._ret = self._target(*self._args, **self._kwargs)\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/tune/trainable/function_trainable.py\", line 115, in <lambda>\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m     training_func=lambda: self._trainable_func(self.config),\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m   File \"/home/nikos/workspace/ray-docker-compose/.venv/lib/python3.8/site-packages/ray/train/base_trainer.py\", line 819, in _trainable_func\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m   File \"/home/nikos/workspace/ray-docker-compose/.venv/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py\", line 332, in _trainable_func\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m   File \"/home/nikos/workspace/ray-docker-compose/.venv/lib/python3.8/site-packages/ray/train/base_trainer.py\", line 729, in train_func\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/train/data_parallel_trainer.py\", line 464, in training_loop\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m     backend_executor.start()\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/train/_internal/backend_executor.py\", line 134, in start\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m     self.worker_group = WorkerGroup(\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/train/_internal/worker_group.py\", line 193, in __init__\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m     self.start()\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/train/_internal/worker_group.py\", line 205, in start\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m     self.add_workers(self.num_workers)\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m   File \"/usr/local/lib/python3.8/dist-packages/ray/train/_internal/worker_group.py\", line 360, in add_workers\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m     metadata = ray.get(new_actor_metadata)\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m \tclass_name: RayTrainWorker\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m \tactor_id: 0d3cd7c996ffd3082245ee0e08000000\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m \tnamespace: 24225e8a-3eb6-4cd7-8d69-b3e54b26f383\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m \tip: 88.197.52.52\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m The actor is dead because its node has died. Node Id: 94d7530cb1f801ef5c9c0fe26cc386c0cebfa082b7a8ebb3485d00fb\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m The actor never ran - it was cancelled before it started running.\n"
     ]
    },
    {
     "ename": "TrainingFailedError",
     "evalue": "The Ray Train run failed. Please inspect the previous error messages for a cause. After fixing the issue (assuming that the error is not caused by your own application logic, but rather an error such as OOM), you can restart the run from scratch or continue this run.\nTo continue this run, you can use: `trainer = TorchTrainer.restore(\"/home/nikos/ray_results/TorchTrainer_2024-01-11_19-52-55\")`.\nTo start a new run that will retry on training failures, set `train.RunConfig(failure_config=train.FailureConfig(max_failures))` in the Trainer's `run_config` with `max_failures > 0`, or `max_failures = -1` for unlimited retries.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRayTaskError(RayActorError)\u001b[0m               Traceback (most recent call last)",
      "\u001b[0;31mRayTaskError(RayActorError)\u001b[0m: \u001b[36mray::TrainTrainable.train()\u001b[39m (pid=323, ip=127.0.0.1, actor_id=36cbebeaf9caa93bc26c198308000000, repr=TorchTrainer)\n  File \"/usr/local/lib/python3.8/dist-packages/ray/tune/trainable/trainable.py\", line 342, in train\n    raise skipped from exception_cause(skipped)\n  File \"/usr/local/lib/python3.8/dist-packages/ray/air/_internal/util.py\", line 88, in run\n    self._ret = self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.8/dist-packages/ray/tune/trainable/function_trainable.py\", line 115, in <lambda>\n    training_func=lambda: self._trainable_func(self.config),\n  File \"/home/nikos/workspace/ray-docker-compose/.venv/lib/python3.8/site-packages/ray/train/base_trainer.py\", line 819, in _trainable_func\n  File \"/home/nikos/workspace/ray-docker-compose/.venv/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py\", line 332, in _trainable_func\n  File \"/home/nikos/workspace/ray-docker-compose/.venv/lib/python3.8/site-packages/ray/train/base_trainer.py\", line 729, in train_func\n  File \"/usr/local/lib/python3.8/dist-packages/ray/train/data_parallel_trainer.py\", line 464, in training_loop\n    backend_executor.start()\n  File \"/usr/local/lib/python3.8/dist-packages/ray/train/_internal/backend_executor.py\", line 134, in start\n    self.worker_group = WorkerGroup(\n  File \"/usr/local/lib/python3.8/dist-packages/ray/train/_internal/worker_group.py\", line 193, in __init__\n    self.start()\n  File \"/usr/local/lib/python3.8/dist-packages/ray/train/_internal/worker_group.py\", line 205, in start\n    self.add_workers(self.num_workers)\n  File \"/usr/local/lib/python3.8/dist-packages/ray/train/_internal/worker_group.py\", line 360, in add_workers\n    metadata = ray.get(new_actor_metadata)\nray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.\n\tclass_name: RayTrainWorker\n\tactor_id: 0d3cd7c996ffd3082245ee0e08000000\n\tnamespace: 24225e8a-3eb6-4cd7-8d69-b3e54b26f383\n\tip: 88.197.52.52\nThe actor is dead because its node has died. Node Id: 94d7530cb1f801ef5c9c0fe26cc386c0cebfa082b7a8ebb3485d00fb\nThe actor never ran - it was cancelled before it started running.",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mTrainingFailedError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[5], line 72\u001b[0m\n\u001b[1;32m     62\u001b[0m \u001b[38;5;66;03m# [4] Define a Ray TorchTrainer to launch `train_func` on all workers\u001b[39;00m\n\u001b[1;32m     63\u001b[0m \u001b[38;5;66;03m# ===================================================================\u001b[39;00m\n\u001b[1;32m     64\u001b[0m ray_trainer \u001b[38;5;241m=\u001b[39m TorchTrainer(\n\u001b[1;32m     65\u001b[0m     train_func,\n\u001b[1;32m     66\u001b[0m     scaling_config\u001b[38;5;241m=\u001b[39mScalingConfig(num_workers\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m2\u001b[39m, use_gpu\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mFalse\u001b[39;00m),\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     70\u001b[0m     run_config\u001b[38;5;241m=\u001b[39mray\u001b[38;5;241m.\u001b[39mtrain\u001b[38;5;241m.\u001b[39mRunConfig(storage_path\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m/ray\u001b[39m\u001b[38;5;124m\"\u001b[39m),\n\u001b[1;32m     71\u001b[0m )\n\u001b[0;32m---> 72\u001b[0m result: ray\u001b[38;5;241m.\u001b[39mtrain\u001b[38;5;241m.\u001b[39mResult \u001b[38;5;241m=\u001b[39m \u001b[43mray_trainer\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     74\u001b[0m \u001b[38;5;66;03m# [5] Load the trained model.\u001b[39;00m\n\u001b[1;32m     75\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m result\u001b[38;5;241m.\u001b[39mcheckpoint\u001b[38;5;241m.\u001b[39mas_directory() \u001b[38;5;28;01mas\u001b[39;00m checkpoint_dir:\n",
      "File \u001b[0;32m~/workspace/ray-docker-compose/.venv/lib/python3.8/site-packages/ray/train/base_trainer.py:640\u001b[0m, in \u001b[0;36mBaseTrainer.fit\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    636\u001b[0m result \u001b[38;5;241m=\u001b[39m result_grid[\u001b[38;5;241m0\u001b[39m]\n\u001b[1;32m    637\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m result\u001b[38;5;241m.\u001b[39merror:\n\u001b[1;32m    638\u001b[0m     \u001b[38;5;66;03m# Raise trainable errors to the user with a message to restore\u001b[39;00m\n\u001b[1;32m    639\u001b[0m     \u001b[38;5;66;03m# or configure `FailureConfig` in a new run.\u001b[39;00m\n\u001b[0;32m--> 640\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m TrainingFailedError(\n\u001b[1;32m    641\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mjoin([restore_msg, TrainingFailedError\u001b[38;5;241m.\u001b[39m_FAILURE_CONFIG_MSG])\n\u001b[1;32m    642\u001b[0m     ) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mresult\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01merror\u001b[39;00m\n\u001b[1;32m    643\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m result\n",
      "\u001b[0;31mTrainingFailedError\u001b[0m: The Ray Train run failed. Please inspect the previous error messages for a cause. After fixing the issue (assuming that the error is not caused by your own application logic, but rather an error such as OOM), you can restart the run from scratch or continue this run.\nTo continue this run, you can use: `trainer = TorchTrainer.restore(\"/home/nikos/ray_results/TorchTrainer_2024-01-11_19-52-55\")`.\nTo start a new run that will retry on training failures, set `train.RunConfig(failure_config=train.FailureConfig(max_failures))` in the Trainer's `run_config` with `max_failures > 0`, or `max_failures = -1` for unlimited retries."
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m Experiment checkpoint syncing has been triggered multiple times in the last 30.0 seconds. A sync will be triggered whenever a trial has checkpointed more than `num_to_keep` times since last sync or if 300 seconds have passed since last sync. If you have set `num_to_keep` in your `CheckpointConfig`, consider increasing the checkpoint frequency or keeping more checkpoints. You can supress this warning by changing the `TUNE_WARN_EXCESSIVE_EXPERIMENT_CHECKPOINT_SYNC_THRESHOLD_S` environment variable.\n",
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m Trials did not complete: [TorchTrainer_42b96_00000]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[36m(TunerInternal pid=12709)\u001b[0m \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Log channel is reconnecting. Logs produced while the connection was down can be found on the head node of the cluster in `ray_client_server_[port].out`\n",
      "2024-01-11 19:53:38,627\tWARNING dataclient.py:403 -- Encountered connection issues in the data channel. Attempting to reconnect.\n",
      "2024-01-11 19:54:08,836\tWARNING dataclient.py:410 -- Failed to reconnect the data channel\n"
     ]
    }
   ],
   "source": [
    "# [1] Encapsulate data preprocessing, training, and evaluation\n",
    "# logic in a training function\n",
    "# ============================================================\n",
    "def train_func(config):\n",
    "    # Datasets\n",
    "    dataset = load_dataset(\"yelp_review_full\")\n",
    "    tokenizer = AutoTokenizer.from_pretrained(\"distilbert-base-uncased\")\n",
    "\n",
    "    def tokenize_function(examples):\n",
    "        return tokenizer(examples[\"text\"], padding=\"max_length\", truncation=True)\n",
    "\n",
    "    small_train_dataset = (\n",
    "        dataset[\"train\"].select(range(1000)).map(tokenize_function, batched=True)\n",
    "    )\n",
    "    small_eval_dataset = (\n",
    "        dataset[\"test\"].select(range(100)).map(tokenize_function, batched=True)\n",
    "    )\n",
    "\n",
    "    # Model\n",
    "    model = AutoModelForSequenceClassification.from_pretrained(\n",
    "        \"distilbert-base-uncased\", num_labels=5, device_map={'':'cpu'}, torch_dtype=torch.float16\n",
    "    )\n",
    "\n",
    "    # Evaluation Metrics\n",
    "    metric = evaluate.load(\"accuracy\")\n",
    "\n",
    "    def compute_metrics(eval_pred):\n",
    "        logits, labels = eval_pred\n",
    "        predictions = np.argmax(logits, axis=-1)\n",
    "        return metric.compute(predictions=predictions, references=labels)\n",
    "\n",
    "    # Hugging Face Trainer\n",
    "    training_args = TrainingArguments(\n",
    "        output_dir=\"test_trainer\",\n",
    "        evaluation_strategy=\"epoch\",\n",
    "        save_strategy=\"epoch\",\n",
    "        report_to=\"none\",\n",
    "        per_device_train_batch_size=4\n",
    "    )\n",
    "\n",
    "    trainer = Trainer(\n",
    "        model=model,\n",
    "        args=training_args,\n",
    "        train_dataset=small_train_dataset,\n",
    "        eval_dataset=small_eval_dataset,\n",
    "        compute_metrics=compute_metrics,\n",
    "    )\n",
    "\n",
    "    # [2] Report Metrics and Checkpoints to Ray Trainentrypoint\n",
    "    # ===============================================\n",
    "    callback = ray.train.huggingface.transformers.RayTrainReportCallback()\n",
    "    trainer.add_callback(callback)\n",
    "\n",
    "    # [3] Prepare Transformers Trainer\n",
    "    # ================================\n",
    "    trainer = ray.train.huggingface.transformers.prepare_trainer(trainer)\n",
    "\n",
    "    # Start Training\n",
    "    trainer.train()\n",
    "\n",
    "\n",
    "# [4] Define a Ray TorchTrainer to launch `train_func` on all workers\n",
    "# ===================================================================\n",
    "ray_trainer = TorchTrainer(\n",
    "    train_func,\n",
    "    scaling_config=ScalingConfig(num_workers=2, use_gpu=False),\n",
    "    # [4a] If running in a multi-node cluster, this is where you\n",
    "    # should configure the run's persistent storage that is accessible\n",
    "    # across all worker nodes.\n",
    "    run_config=ray.train.RunConfig(storage_path=\"/ray\"),\n",
    ")\n",
    "result: ray.train.Result = ray_trainer.fit()\n",
    "\n",
    "# [5] Load the trained model.\n",
    "with result.checkpoint.as_directory() as checkpoint_dir:\n",
    "    checkpoint_path = os.path.join(\n",
    "        checkpoint_dir,\n",
    "        ray.train.huggingface.transformers.RayTrainReportCallback.CHECKPOINT_NAME,\n",
    "    )\n",
    "    model = AutoModelForSequenceClassification.from_pretrained(checkpoint_path)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (myenv)",
   "language": "python",
   "name": "myenv"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
